FROM python:3.7-alpine

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

ENV FLASK_RUN_HOST 0.0.0.0

RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "controller.py" ]
EXPOSE 5000