FROM maven:3-jdk-8 AS build

WORKDIR /build
COPY pom.xml /build
RUN mvn dependency:go-offline

COPY src/main /build/src/main
RUN mvn package

FROM openjdk:8

COPY --from=build /build/target/rspls*.jar /srv/app.jar
COPY --from=build /build/src/main/resources/ /srv/resources

CMD exec java $JAVA_OPTS -jar /srv/app.jar
EXPOSE 8080
