FROM python:3-alpine
WORKDIR /srv
COPY requirements.txt .
RUN pip install -r requirements.txt
# Use this if requirements.txt doesn't exist
# RUN pip install Flask flask_cors
COPY main.py app.py
# Set FLASK_APP if the file is not app.py
# ENV FLASK_APP
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_RUN_PORT 8080
EXPOSE 8080
CMD [ "flask", "run" ]