FROM gradle:6.0-jdk8 AS build

WORKDIR /build
COPY . /build/
RUN gradle build --no-daemon

FROM openjdk:8-jre-slim

WORKDIR /srv

COPY --from=build /build/build/libs/*.jar /srv/app.jar

CMD exec java $JAVA_OPTS -jar /srv/app.jar
EXPOSE 8080
